[global]
mraauthor=["jotego"]

[parse]
sourcefile="cps1.cpp"
skip.descriptions=[
    "Cadillacs",
    "1.5",
    "Kurau II",
    "Punisher",
]
skip.bootlegs=true

[buttons]
count=$JTFRAME_BUTTONS

[dipsw]
delete=[ "Unused" ]