[global]
mraauthor=["jotego"]

[parse]
sourcefile="cps1.cpp"
skip.machines=[ "dino", "wof", "mbombrd", "punisher" ]
skip.descriptions=[
    "Cadillacs",
    "1.5",
    "Kurau II",
    "Punisher",
]
skip.bootlegs=true

[buttons]
Names = [
    { machine="1941",     names="Shoot,Bomb"},
    { machine="unsquad",  names="Shoot,Bomb"},
    { machine="captcomm", names="Attack,Jump"},
    { machine="cawing",   names="Shoot,Bomb"},
    { machine="mtwins",   names="Attack,Jump,Special"},
    { machine="ghouls",   names="Attack,Jump"},
    { machine="dynwars",  names="Attack left,Attack right,Special"},
    { machine="ffight",   names="Attack,Jump"},
    { machine="forgottn", names="Shoot,Rotate left,Rotate right"},
    { machine="knights",  names="Slay,Jump"},
    { machine="kod",      names="Slay,Jump"},
    { machine="msword",   names="Slay,Jump"},
    { machine="megaman",  names="Attack,Jump"},
    { machine="mercs",    names="Shoot,Bomb"},
    { machine="mbombrd",  names="Hit,Grab,Jump"},
    { machine="nemo",     names="Attack,Jump"},
    { machine="pang3",    names="Shoot"},
    { machine="pnickj",   names="Rotate left,Rotate right"},
    { machine="sf2",      names="LP,MP,SP,LK,MK,HK"},
    { machine="sf2ce",    names="LP,MP,SP,LK,MK,HK"},
    { machine="strider",  names="Attack,Jump"},
    { machine="varth",    names="Shoot,Bomb"},
    { machine="willow",   names="Attack,Jump"},
    { machine="wof",      names="Attack,Jump"},
]


[dipsw]
delete=[ "Unused" ]