[global]
mraauthor=["jotego"]

[parse]
sourcefile="cps1.cpp"
mustbe.devices=["qsound_hle"]
skip.bootlegs=true

[dipsw]
delete=[ "Unused" ]

[rom]

regions=[
    # The Q-Sound may fail because the dl-1425.bin length is larger than 0x2000
    { name="gfx", width=64 },
    { name="firmware", files=[ { name="dl-1425.bin", crc="d6cf5ef5", size=0x2000 } ] },
    { name="aboardplds", skip=true },
    { name="bboardplds", skip=true },
    { name="cboardplds", skip=true },
    { name="dboardplds", skip=true },
]

order=[
    "maincpu", "audiocpu", "qsound",
    "gfx","firmware"
]